#!/usr/bin/env python

import sys, getopt
import iview

def usage():
	print("""usage:
	-d, --download <url>	download a program
	-p, --programme		print the iView programme (URL in parentheses)
	-s, --handshake		print iView handshake (auth) information
	-h, --help		this page""")

def programme():
	iview.do_handshake()
	iview.get_programme()

	for name, programs in iview.comm.programme.iteritems():
		print(name + ':')
		for p in programs:
			print('\t' + p['title'] + '\t(' + p['url'] + ')')

def handshake():
	iview.do_handshake()

	from iview.comm import auth
	print 'iView auth data:'
	print '\tToken:', auth['token']
	print '\tRTMP URL:', auth['rtmp_url']
	print '\tUnmetered:', str(auth['free'])

def download(url):
	iview.do_handshake()
	iview.fetch.fetch_program(url, execvp=True)

try:
	opts, args = getopt.getopt(sys.argv[1:], 'd:psh', ['download=', 'programme', 'program', 'handshake', 'help'])
	if not len(opts) > 0:
		raise getopt.GetoptError('Not enough arguments')
except getopt.GetoptError, err:
	usage()
	sys.exit(2)

for o, a in opts:
	if o in ('-p', '--programme', '--program'):
		programme()
	elif o in ('-s', '--handshake'):
		handshake()
	elif o in ('-d', '--download'):
		download(a)
	elif o in ('-h', '--help'):
		usage()
		sys.exit(2)

